=== codecurve/fieldml.fieldml-java2/trunk/C/src/docs/Fieldml_0.2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="fieldml" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="SimpleMapEntryType">
        <xs:attribute name="key" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="SimpleMapType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="SimpleMapEntry" type="SimpleMapEntryType" />
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="DefaultSimpleMapType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="SimpleMapEntry" type="SimpleMapEntryType" />
        </xs:choice>
        <xs:attribute name="default" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="SimpleListEntryType">
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="SimpleListType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="entry" type="SimpleListEntryType" />
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ContiguousEnsembleBoundsType">
        <xs:attribute name="valueCount" type="xs:positiveInteger" />
    </xs:complexType>
    <xs:complexType name="EnsembleDomainBoundsType">
        <xs:choice minOccurs="1" maxOccurs="1">
            <xs:element name="ContiguousEnsembleBounds" type="ContiguousEnsembleBoundsType" />
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="EnsembleDomainType">
        <xs:all>
            <xs:element name="bounds" type="EnsembleDomainBoundsType" minOccurs="1" maxOccurs="1" />
            <xs:element name="markup" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="MeshDomainType">
        <xs:all>
            <xs:element name="bounds" type="EnsembleDomainBoundsType" minOccurs="1" maxOccurs="1" />
            <xs:element name="markup" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
            <xs:element name="shapes" type="DefaultSimpleMapType" minOccurs="1" maxOccurs="1" />
            <xs:element name="pointConnectivity" type="SimpleMapType" minOccurs="1" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="xiComponentDomain" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="VariableEvaluatorType">
        <xs:all>
            <xs:element name="markup" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
            <xs:element name="parameterDomains" type="SimpleListType" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="valueDomain" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="ContinuousReferenceEvaluatorType">
        <xs:all>
            <xs:element name="markup" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
            <xs:element name="aliases" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="valueDomain" type="xs:string" />
        <xs:attribute name="evaluator" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="PiecewiseEvaluatorType">
        <xs:all>
            <xs:element name="markup" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
            <xs:element name="elementEvaluators" type="DefaultSimpleMapType" minOccurs="0" maxOccurs="1" />
            <xs:element name="aliases" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="valueDomain" type="xs:string" />
        <xs:attribute name="indexDomain" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="SemidenseDataType">
        <xs:all>
            <xs:element name="denseIndexes" type="SimpleListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="sparseIndexes" type="SimpleListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="dataLocation" type="DataLocationType" minOccurs="0" maxOccurs="1" />
            <xs:element name="swizzle" type="SwizzleType" minOccurs="0" maxOccurs="1" />
            <xs:element name="inlineData" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:list itemType="xs:decimal"/>
                </xs:simpleType>
            </xs:element>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="FileDataType">
        <xs:attribute name="file" type="xs:string" />
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="offset" type="xs:nonNegativeInteger" />
    </xs:complexType>
    <xs:complexType name="InlineDataType">
        <xs:simpleContent>
            <xs:extension base="xs:string" />
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="SwizzleType">
        <xs:simpleContent>
            <xs:extension base="xs:string" />
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="DataLocationType">
        <xs:choice>
            <xs:element name="fileData" type="FileDataType" />
            <xs:element name="inlineData" type="InlineDataType" />
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ParametersType">
        <xs:all>
            <xs:element name="markup" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
            <xs:element name="SemidenseData" type="SemidenseDataType" minOccurs="1" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="valueDomain" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="AggregateEvaluatorType">
        <xs:all>
            <xs:element name="markup" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
            <xs:element name="sourceFields" type="SimpleMapType" minOccurs="1" maxOccurs="1" />
            <xs:element name="aliases" type="SimpleMapType" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="valueDomain" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="RegionType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="EnsembleDomain" type="EnsembleDomainType" />
            <xs:element name="MeshDomain" type="MeshDomainType" />
            <xs:element name="ContinuousVariableEvaluator" type="VariableEvaluatorType" />
            <xs:element name="EnsembleVariableEvaluator" type="VariableEvaluatorType" />
            <xs:element name="ContinuousReferenceEvaluator" type="ContinuousReferenceEvaluatorType" />
            <xs:element name="ContinuousPiecewiseEvaluator" type="PiecewiseEvaluatorType" />
            <xs:element name="EnsemblePiecewiseEvaluator" type="PiecewiseEvaluatorType" />
            <xs:element name="ContinuousParameters" type="ParametersType" />
            <xs:element name="EnsembleParameters" type="ParametersType" />
            <xs:element name="ContinuousAggregateEvaluator" type="AggregateEvaluatorType" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
    <xs:element name="fieldml">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element name="Region" type="RegionType" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== codecurve/fieldml.fieldml-java2/trunk/C/data/test_example3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<fieldml version="0.2_alpha" xsi:noNamespaceSchemaLocation="Fieldml_0.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <!--
 A single-component field defined over a three element mesh.
 The first element is bilinear-Lagrange.
 The second element is element-constant.
 The third element is globally constant.
 
 In this version, there is a common dof store indexed by common dof map, which is wrapped
 in interpolation-specific parameter evaluators.
  -->
 <Region name="dof_example_3">
  <EnsembleDomain name="test.mesh_nodes">
   <bounds>
    <ContiguousEnsembleBounds valueCount="8"/>
   </bounds>
  </EnsembleDomain>
  <MeshDomain name="test.mesh" xiComponentDomain="library.ensemble.xi.2d">
   <bounds>
    <ContiguousEnsembleBounds valueCount="3"/>
   </bounds>
   <shapes default="library.shape.square"/>
   <pointConnectivity>
    <SimpleMapEntry key="test.bilinear_connectivity" value="library.local_nodes.square.2x2"/>
   </pointConnectivity>
  </MeshDomain>
  <EnsembleParameters name="test.bilinear_connectivity" valueDomain="test.mesh_nodes">
   <SemidenseData>
    <denseIndexes>
     <entry value="library.local_nodes.square.2x2"/>
     <entry value="test.mesh.elements"/>
    </denseIndexes>
    <dataLocation>
     <inlineData>
1 2 5 6
2 3 6 7
3 4 7 8</inlineData>
    </dataLocation>
   </SemidenseData>
  </EnsembleParameters>
  <EnsembleDomain name="test.dof_number">
   <bounds>
    <ContiguousEnsembleBounds valueCount="6"/>
   </bounds>
  </EnsembleDomain>
  <ContinuousParameters name="test.dof_params" valueDomain="library.real.1d">
   <SemidenseData>
    <denseIndexes>
     <entry value="test.dof_number"/>
    </denseIndexes>
    <dataLocation>
     <inlineData>0.0 0.5 1.0 1.5 2.0 3.0 </inlineData>
    </dataLocation>
   </SemidenseData>
  </ContinuousParameters>
  <EnsembleDomain name="test.dof_type">
   <bounds>
    <ContiguousEnsembleBounds valueCount="3"/>
   </bounds>
  </EnsembleDomain>
  <EnsembleParameters name="test.dof_indexes" valueDomain="test.dof_number">
   <SemidenseData>
    <sparseIndexes>
     <entry value="test.dof_type"/>
     <entry value="test.mesh_nodes"/>
     <entry value="test.mesh.elements"/>
    </sparseIndexes>
    <dataLocation>
     <inlineData>
1 1 1 2
1 1 2 2
1 1 3 2
1 2 1 3
1 2 2 3
1 2 3 3
1 3 1 4
1 3 2 4
1 3 3 4
1 4 1 5
1 4 2 5
1 4 3 5

2 1 2 6
2 2 2 6
2 3 2 6
2 4 2 6
2 5 2 6
2 6 2 6
2 7 2 6
2 8 2 6

3 1 1 1
3 2 1 1
3 3 1 1
3 4 1 1
3 5 1 1
3 6 1 1
3 7 1 1
3 8 1 1
3 1 2 1
3 2 2 1
3 3 2 1
3 4 2 1
3 5 2 1
3 6 2 1
3 7 2 1
3 8 2 1
3 1 3 1
3 2 3 1
3 3 3 1
3 4 3 1
3 5 3 1
3 6 3 1
3 7 3 1
3 8 3 1</inlineData>
    </dataLocation>
   </SemidenseData>
  </EnsembleParameters>
  <ContinuousDomain name="1"/>
  <ContinuousDomain name="2"/>
  <ContinuousDomain name="3"/>
  <ContinuousReferenceEvaluator name="test.nodal_indexes" evaluator="test.dof_indexes" valueDomain="test.dof_number">
   <aliases>
    <SimpleMapEntry key="test.dof_type" value="1"/>
    <SimpleMapEntry key="test.mesh.elements" value="1"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.element_indexes" evaluator="test.dof_indexes" valueDomain="test.dof_number">
   <aliases>
    <SimpleMapEntry key="test.dof_type" value="2"/>
    <SimpleMapEntry key="test.mesh_nodes" value="1"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.global_indexes" evaluator="test.dof_indexes" valueDomain="test.dof_number">
   <aliases>
    <SimpleMapEntry key="test.dof_type" value="3"/>
    <SimpleMapEntry key="test.mesh_nodes" value="1"/>
    <SimpleMapEntry key="test.mesh.elements" value="1"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.nodal_params" evaluator="test.dof_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.dof_number" value="test.nodal_indexes"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.element_params" evaluator="test.dof_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.dof_number" value="test.element_indexes"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.global_params" evaluator="test.dof_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.dof_number" value="test.global_indexes"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.bilinear_nodal_params" evaluator="test.nodal_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.mesh_nodes" value="test.bilinear_connectivity"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.bilinear_interpolator" evaluator="library.fem.bilinear_lagrange" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="library.xi.2d" value="test.mesh.xi"/>
    <SimpleMapEntry key="library.parameters.bilinear_lagrange" value="test.bilinear_nodal_params"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousPiecewiseEvaluator name="test.field" indexDomain="test.mesh.elements" valueDomain="library.real.1d">
   <elementEvaluators>
    <SimpleMapEntry key="1" value="test.bilinear_interpolator"/>
    <SimpleMapEntry key="2" value="test.element_params"/>
    <SimpleMapEntry key="3" value="test.global_params"/>
   </elementEvaluators>
  </ContinuousPiecewiseEvaluator>
 </Region>
</fieldml>

=== codecurve/fieldml.fieldml-java2/trunk/C/data/test_example1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<fieldml version="0.2_alpha" xsi:noNamespaceSchemaLocation="Fieldml_0.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <Region name="dof_example_1">
  <EnsembleDomain name="test.mesh_nodes">
   <bounds>
    <ContiguousEnsembleBounds valueCount="8"/>
   </bounds>
  </EnsembleDomain>
  <MeshDomain name="test.mesh" xiComponentDomain="library.ensemble.xi.2d">
   <bounds>
    <ContiguousEnsembleBounds valueCount="3"/>
   </bounds>
   <shapes default="library.shape.square"/>
   <pointConnectivity>
    <SimpleMapEntry key="test.bilinear_connectivity" value="library.local_nodes.square.2x2"/>
   </pointConnectivity>
  </MeshDomain>
  <EnsembleParameters name="test.bilinear_connectivity" valueDomain="test.mesh_nodes">
   <SemidenseData>
    <denseIndexes>
     <entry value="library.local_nodes.square.2x2"/>
     <entry value="test.mesh.elements"/>
    </denseIndexes>
    <dataLocation>
     <inlineData>
1 2 5 6
2 3 6 7
3 4 7 8</inlineData>
    </dataLocation>
   </SemidenseData>
  </EnsembleParameters>
  <ContinuousParameters name="test.nodal_params" valueDomain="library.real.1d">
   <SemidenseData>
    <sparseIndexes>
     <entry value="test.mesh_nodes"/>
    </sparseIndexes>
    <dataLocation>
     <inlineData>1 0.0 2 0.5 3 1.0 4 1.5 </inlineData>
    </dataLocation>
   </SemidenseData>
  </ContinuousParameters>
  <ContinuousParameters name="test.element_params" valueDomain="library.real.1d">
   <SemidenseData>
    <sparseIndexes>
     <entry value="test.mesh.elements"/>
    </sparseIndexes>
    <dataLocation>
     <inlineData>2 2.0 </inlineData>
    </dataLocation>
   </SemidenseData>
  </ContinuousParameters>
  <ContinuousParameters name="test.global_params" valueDomain="library.real.1d">
   <SemidenseData>
    <dataLocation>
     <inlineData>3.0 </inlineData>
    </dataLocation>
   </SemidenseData>
  </ContinuousParameters>
  <ContinuousReferenceEvaluator name="test.bilinear_nodal_params" evaluator="test.nodal_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.mesh_nodes" value="test.bilinear_connectivity"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.bilinear_interpolator" evaluator="library.fem.bilinear_lagrange" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="library.xi.2d" value="test.mesh.xi"/>
    <SimpleMapEntry key="library.parameters.bilinear_lagrange" value="test.bilinear_nodal_params"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousPiecewiseEvaluator name="test.field" indexDomain="test.mesh.elements" valueDomain="library.real.1d">
   <elementEvaluators>
    <SimpleMapEntry key="1" value="test.bilinear_interpolator"/>
    <SimpleMapEntry key="2" value="test.element_params"/>
    <SimpleMapEntry key="3" value="test.global_params"/>
   </elementEvaluators>
  </ContinuousPiecewiseEvaluator>
 </Region>
</fieldml>

=== codecurve/fieldml.fieldml-java2/trunk/C/data/test_example2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<fieldml version="0.2_alpha" xsi:noNamespaceSchemaLocation="Fieldml_0.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <!--
 A single-component field defined over a three element mesh.
 The first element is bilinear-Lagrange.
 The second element is element-constant.
 The third element is globally constant.
 
 In this version, there is a common dof store indexed by separate interpolation-specific maps, each
 of which is wrapped in an interpolation-specific parameter evaluator.
  -->
 <Region name="dof_example_2">
  <EnsembleDomain name="test.mesh_nodes">
   <bounds>
    <ContiguousEnsembleBounds valueCount="8"/>
   </bounds>
  </EnsembleDomain>
  <MeshDomain name="test.mesh" xiComponentDomain="library.ensemble.xi.2d">
   <bounds>
    <ContiguousEnsembleBounds valueCount="3"/>
   </bounds>
   <shapes default="library.shape.square"/>
   <pointConnectivity>
    <SimpleMapEntry key="test.bilinear_connectivity" value="library.local_nodes.square.2x2"/>
   </pointConnectivity>
  </MeshDomain>
  <EnsembleParameters name="test.bilinear_connectivity" valueDomain="test.mesh_nodes">
   <SemidenseData>
    <denseIndexes>
     <entry value="library.local_nodes.square.2x2"/>
     <entry value="test.mesh.elements"/>
    </denseIndexes>
    <dataLocation>
     <inlineData>
1 2 5 6
2 3 6 7
3 4 7 8</inlineData>
    </dataLocation>
   </SemidenseData>
  </EnsembleParameters>
  <EnsembleDomain name="test.dof_number">
   <bounds>
    <ContiguousEnsembleBounds valueCount="6"/>
   </bounds>
  </EnsembleDomain>
  <ContinuousParameters name="test.dof_params" valueDomain="library.real.1d">
   <SemidenseData>
    <denseIndexes>
     <entry value="test.dof_number"/>
    </denseIndexes>
    <dataLocation>
     <inlineData>0.0 0.5 1.0 1.5 2.0 3.0 </inlineData>
    </dataLocation>
   </SemidenseData>
  </ContinuousParameters>
  <EnsembleParameters name="test.nodal_indexes" valueDomain="test.dof_number">
   <SemidenseData>
    <sparseIndexes>
     <entry value="test.mesh_nodes"/>
    </sparseIndexes>
    <dataLocation>
     <inlineData>1 2 2 3 3 4 4 5 </inlineData>
    </dataLocation>
   </SemidenseData>
  </EnsembleParameters>
  <EnsembleParameters name="test.element_indexes" valueDomain="test.dof_number">
   <SemidenseData>
    <sparseIndexes>
     <entry value="test.mesh.elements"/>
    </sparseIndexes>
    <dataLocation>
     <inlineData>2 6 </inlineData>
    </dataLocation>
   </SemidenseData>
  </EnsembleParameters>
  <EnsembleParameters name="test.global_indexes" valueDomain="test.dof_number">
   <SemidenseData>
    <dataLocation>
     <inlineData>1 </inlineData>
    </dataLocation>
   </SemidenseData>
  </EnsembleParameters>
  <ContinuousReferenceEvaluator name="test.nodal_params" evaluator="test.dof_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.dof_number" value="test.nodal_indexes"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.element_params" evaluator="test.dof_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.dof_number" value="test.element_indexes"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.global_params" evaluator="test.dof_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.dof_number" value="test.global_indexes"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.bilinear_nodal_params" evaluator="test.nodal_params" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="test.mesh_nodes" value="test.bilinear_connectivity"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousReferenceEvaluator name="test.bilinear_interpolator" evaluator="library.fem.bilinear_lagrange" valueDomain="library.real.1d">
   <aliases>
    <SimpleMapEntry key="library.xi.2d" value="test.mesh.xi"/>
    <SimpleMapEntry key="library.parameters.bilinear_lagrange" value="test.bilinear_nodal_params"/>
   </aliases>
  </ContinuousReferenceEvaluator>
  <ContinuousPiecewiseEvaluator name="test.field" indexDomain="test.mesh.elements" valueDomain="library.real.1d">
   <elementEvaluators>
    <SimpleMapEntry key="1" value="test.bilinear_interpolator"/>
    <SimpleMapEntry key="2" value="test.element_params"/>
    <SimpleMapEntry key="3" value="test.global_params"/>
   </elementEvaluators>
  </ContinuousPiecewiseEvaluator>
 </Region>
</fieldml>
